# Generated by Django 4.1.2 on 2022-11-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('documento', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=12)),
                ('telefono', models.IntegerField(max_length=15)),
                ('fechanacimiento', models.DateField()),
                ('estadocivil', models.CharField(max_length=20)),
            ],
        ),
    ]
